{
	"version": 1517500054,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/title-sheet0.png",
		"images/title-sheet1.png",
		"images/listeunivers-sheet0.png",
		"images/timetxt.png",
		"images/sf-sheet0.png",
		"images/goku-sheet0.png",
		"images/goku-sheet1.png",
		"images/enemy-sheet0.png",
		"images/turnball1-sheet0.png",
		"images/turnball1-sheet1.png",
		"images/button4-sheet0.png",
		"images/turnball2-sheet0.png",
		"images/turnball2-sheet1.png",
		"images/attackicon-default-000.jpg",
		"images/attackicon-default-001.jpg",
		"images/attackicon-default-002.jpg",
		"images/attackicon-default-003.jpg",
		"images/attackicon-sheet0.png",
		"images/attackicon-sheet1.png",
		"images/hpbar-sheet0.png",
		"images/timecommand-sheet0.png",
		"images/energybar-sheet0.png",
		"images/hpbarshadow-sheet0.png",
		"images/hpenemy-sheet0.png",
		"images/hpenemybarshadow-sheet0.png",
		"images/playerkiblast-sheet0.png",
		"images/aura-sheet0.png",
		"images/aura2-sheet0.png",
		"images/aura2-sheet1.png",
		"images/aura2-sheet2.png",
		"images/commandbuttons-sheet0.png",
		"images/bigbangattackki-sheet0.png",
		"images/bigbangattackki-sheet1.png",
		"images/bigbangattackki-sheet2.png",
		"images/fisthit-sheet0.png",
		"images/fisthit-sheet1.png",
		"images/fisthit-sheet2.png",
		"images/kameha-sheet0.png",
		"images/beam-sheet0.png",
		"images/kame-sheet0.png",
		"images/dust-sheet0.png",
		"images/bigexplosion-sheet0.png",
		"images/genki-sheet0.png",
		"images/label-sheet0.png",
		"images/chargelv-sheet0.png",
		"images/iconlv-sheet0.png",
		"images/iconlv-sheet1.png",
		"images/celownik-sheet0.png",
		"images/enemyhpborder-sheet0.png",
		"images/jednostki.png",
		"images/damagetext.png",
		"images/label2-sheet0.png",
		"images/portret-sheet0.png",
		"images/portret-sheet1.png",
		"images/thumb-sheet0.png",
		"images/plus-sheet0.png",
		"images/plus-sheet1.png",
		"images/minus-sheet0.png",
		"images/minus-sheet1.png",
		"images/wikibackground-sheet0.png",
		"images/tiledbackground.png",
		"images/zrzutekranu-sheet0.png",
		"images/tiledbackground2.png",
		"images/e68f0e651b3e06752d8b387e09fb4c-sheet0.png",
		"images/sprite-sheet0.png",
		"images/levelsbutton-sheet0.png",
		"images/levelsbutton-sheet1.png",
		"images/font2.png",
		"images/leveltxt.png",
		"media/db select.m4a",
		"media/db select.ogg",
		"media/db turn.m4a",
		"media/db turn.ogg",
		"media/puch.m4a",
		"media/punch.ogg",
		"media/dbz big blast).m4a",
		"media/dbz big blast).ogg",
		"media/defhit.m4a",
		"media/defhit.ogg",
		"media/dbz hit punch ground.m4a",
		"media/dbz hit punch ground.ogg",
		"media/punch2.m4a",
		"media/punch2.ogg",
		"media/dragonball z sound effects (480p.kameha).m4a",
		"media/dragonball z sound effects (480p.kameha).ogg",
		"media/dragonball z sound effects (charge big bang).m4a",
		"media/dragonball z sound effects (charge big bang).ogg",
		"media/dragonball z sound effects (click).m4a",
		"media/dragonball z sound effects (click).ogg",
		"media/duel.m4a",
		"media/duel.ogg",
		"media/dragonball z sound effects (fly).m4a",
		"media/dragonball z sound effects (fly).ogg",
		"media/dragonball z sound effects (gain).m4a",
		"media/dragonball z sound effects (gain).ogg",
		"media/dragonball z sound effects (kiblast).m4a",
		"media/dragonball z sound effects (kiblast).ogg",
		"media/dragonball z sound effects (kiblast2).m4a",
		"media/dragonball z sound effects (kiblast2).ogg",
		"media/punch3.m4a",
		"media/punch3.ogg",
		"media/punch4.m4a",
		"media/punch4.ogg",
		"media/dragonball z sound effects (teleport).m4a",
		"media/dragonball z sound effects (teleport).ogg",
		"media/explosion.m4a",
		"media/explosion.ogg",
		"media/kame hame ha! 1.m4a",
		"media/kame hame ha! 1.ogg",
		"media/super saiyan transformacion.m4a",
		"media/super saiyan transformacion.ogg",
		"media/teleport.m4a",
		"media/teleport.ogg",
		"media/crows.m4a",
		"media/crows.ogg",
		"media/intros_003.m4a",
		"media/intros_003.ogg",
		"media/revontuelt.m4a",
		"media/revontuelt.ogg",
		"media/friedman.m4a",
		"media/friedman.ogg",
		"media/lynch.m4a",
		"media/lynch.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"animate.min.css"
	]
}