{
	"version": 1517224361,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/spawner-sheet0.png",
		"images/texttlo.png",
		"images/icon-sheet0.png",
		"images/icon-sheet1.png",
		"images/obraz-sheet0.png",
		"images/button-sheet0.png",
		"images/button-sheet1.png",
		"images/tiledbackground.png",
		"images/spritefont.png",
		"images/obraz2-sheet0.png",
		"images/spritefont2.png",
		"images/spritefont3.png",
		"images/plik-sheet0.png",
		"images/plik-sheet1.png",
		"images/dalej-sheet0.png",
		"images/dalej-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/desttext.png",
		"images/backgroundsprite-sheet0.png",
		"images/back.png",
		"images/alien-sheet0.png",
		"images/alien-sheet1.png",
		"images/tiledbackground2.png",
		"media/computer calculation notification1.m4a",
		"media/computer calculation notification1.ogg",
		"media/computer calculation notification2.m4a",
		"media/computer calculation notification2.ogg",
		"media/sketchy digital button hit 2.m4a",
		"media/sketchy digital button hit 2.ogg",
		"media/incoming message 5.m4a",
		"media/incoming message 5.ogg",
		"media/end.m4a",
		"media/end.ogg",
		"media/pop.m4a",
		"media/pop.ogg",
		"media/coin notificaiton.m4a",
		"media/coin notificaiton.ogg",
		"media/typecpu.m4a",
		"media/typecpu.ogg",
		"media/exploracja.m4a",
		"media/exploracja.ogg",
		"media/decyzja.m4a",
		"media/decyzja.ogg",
		"media/koniec.m4a",
		"media/koniec.ogg",
		"media/trust issues.m4a",
		"media/trust issues.ogg",
		"media/intro.m4a",
		"media/intro.ogg",
		"media/intro (2).m4a",
		"media/intro (2).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}